name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod download
      - name: Format
        run: |
          fmt_out=$(gofmt -l $(git ls-files '*.go'))
          if [ -n "$fmt_out" ]; then
            echo "Go files not formatted:" && echo "$fmt_out" && exit 1
          fi
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod download
      - name: Run integration tests
        run: go test -tags=integration ./...
