name: Go CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod download
      - name: Format
        run: |
          gofmt -w $(git ls-files '*.go')
          if [ -n "$(git status --porcelain)" ]; then
            echo "Go files not formatted" && git diff && exit 1
          fi
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
  integration-tests:
    name: Integration Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod download
      - name: Run integration tests
        run: go test -tags=integration ./tests/integration
